heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  volume_snapshot:
    type: string
    description: volume snapshot _id
  key_name:
    type: string
    description: SSH key to connect to the servers
  security_groups:
    type: string
    description: Security groups id list
  flavor:
    type: string
    description: flavor used by the servers
  pool_id:
    type: string
    description: Pool to contact
  user_data:
    type: string
    description: Server user_data
  metadata:
    type: json
  network:
    type: string
    description: Network used by the server

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      block_device_mapping:
        - device_name: vda
          delete_on_termination: true
          volume_id: { get_resource: volume }
      key_name: {get_param: key_name}
      security_groups: {get_param: security_groups}
      networks: [{network: {get_param: network} }]
  volume:
    type: OS::Cinder::Volume
    properties:
      snapshot_id: { get_param: volume_snapshot }
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: 80

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
  lb_member:
    description: LB member details.
    value: { get_attr: [member, show] }
